import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar'
import { Roboto } from 'next/font/google'
 
const roboto = Roboto({
  weight: '800',
  subsets: ['latin'],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geist = Geist({
  subsets: ['latin'],
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // className={`${geistMono.className} h-full antialiased`}
      className={roboto.className}
    >
      <body className="min-h-full flex flex-col">
        {/* <Navbar /> */}
        <main className="min-h-dvh">
        {children}
        </main>
        {/* <footer className="text-center text-4xl my-5">
          This is Footer Section
        </footer> */}
        </body>
    </html>
  );
}
